Kitware/VolView

- src/App.vue
- src/components/VtkTwoView.vue
- src/store/datasets.js
- src/store/widgets.js
- src/widgets/widget.js
FYI @timthirion this commit gives a general idea of how to refactor to namespace a module, though the visualization module will have a lot more changes.
Closes #12
> refactor(widgets): Namespace widgets module

- src/App.vue
- src/components/ModelBrowser.vue
- src/components/PatientBrowser.vue
- src/components/VolumeRendering.vue
- src/components/VtkThreeView.vue
- src/components/VtkTwoView.vue
- src/mixins/VtkView.js
- src/store/datasets.js
- src/store/visualization.js
- src/widgets/paint.js
- src/widgets/slicingCrosshairs.js
> WIP: Various Bug Fixes

- README.md
> docs(README): Add Zenodo badge

- .eslintrc.js
- package-lock.json
- package.json
- src/App.vue
- src/components/MeasurementsModule.vue
- src/components/VtkTwoView.vue
- src/store/datasets.js
- src/store/measurements.js
- src/store/widgets.js
- src/vtk/RulerWidget/behavior.js
- src/vtk/RulerWidget/index.js
- src/vtk/RulerWidget/state.js
- src/vtk/SVGCircleHandleRepresentation/index.js
- src/vtk/SVGLabelRepresentation/index.js
- src/vtk/SVGLineRepresentation/index.js
- src/widgets/context.js
- src/widgets/reactivity.js
- src/widgets/ruler.js
- src/widgets/widgetHooks.js
- src/widgets/widgetProvider.js
@timthirion This is a sketch of a (hopefully) more flexible widget setup.
For an (unfinished) sketch of what widgets would be like, check out [newRuler.js](https://github.com/KitwareMedical/paraview-medical/blob/new-widgets/src/widgets/newRuler.js). It's incomplete, but hopefully can give a sense of what sort of widget API exists.
For a more complete API, check out [context.js](https://github.com/KitwareMedical/paraview-medical/blob/new-widgets/src/widgets/context.js#L53). That gives a more comprehensive overview of the hooks.
I ended up sketching out something that is similar to vue 3, only because (1) we are using vue, and (2) I think the concepts fit nicely with how we want to use widgets.
I'll add more information here later. For now, let me know if you have questions or concerns …
> widget architecture

- public/global.css
- src/components/AiModule.vue
- src/components/AnnotationsModule.vue
- src/components/App.vue
- src/components/ImageListCard.vue
- src/components/MessageCenter.vue
- src/components/ModulePanel.vue
- src/components/PatientBrowser.vue
- src/components/VolumeRendering.vue
- fix selection coloring in dark mode
- highlight annotation headers
- removed redundant css class, and make modules fill the vertical space
> Some UI tweaks

- src/components/ColorFunctionSlider.vue
- src/components/ItemGroup.vue
- src/components/VolumeRendering.vue
- src/components/VtkThreeView.vue
- src/composables/useSceneBuilder.ts
- src/composables/useVTKCallback.ts
- src/shims-vtk.d.ts
- src/store/__tests__/view-configs.spec.ts
- src/store/datasets.ts
- src/store/view-configs.ts
- src/store/views-3D.ts
- src/vtk/PiecewiseWidget/index.js
- fixes colormap handling
- adds colormap slider
> [WIP] Volume colormap and opacity improvements

- src/components/App.vue
- src/components/DataBrowser.vue
- src/components/ModulePanel.vue
- src/components/Settings.vue
- settings is accessible at the bottom of the tool strip
- data browser no longer has a collection switcher
> Move settings panel and clean up data browser

- src/components/App.vue
- src/components/ColorFunctionSlider.vue
- src/components/LayoutGrid.vue
- src/components/ModulePanel.vue
- src/components/SliceSlider.vue
- src/components/VtkThreeView.vue
- src/components/VtkTwoView.vue
- src/components/styles/utils.css
- src/components/styles/vtk-view.css
- src/shims-vtk.d.ts
- src/vtk/LPSView3DProxy/index.js
- improve view styles (especially the slider and background colors)
- adjust module panel styles
> Style improvements

- src/components/App.vue
- src/components/MeasurementsList.vue
- src/components/styles/utils.css
- src/components/tools/RulerTool.vue
- src/components/tools/ruler/RulerSVG2D.vue
- src/constants.ts
- src/core/tools/ruler.ts
- src/store/tools/rulers.ts
Adds a rotating list of colors to the rulers.
> feat(Rulers): add color support

- src/components/App.vue
- src/components/MeasurementsList.vue
- src/components/tools/RulerTool.vue
- src/components/tools/ruler/RulerWidget2D.vue
- src/core/id.ts
- src/core/provider.ts
- src/core/proxies.ts
- src/core/tools/__tests__/paint.spec.ts
- src/core/tools/__tests__/ruler.spec.ts
- src/core/tools/paint/index.ts
- src/core/tools/ruler.ts
- src/global.d.ts
- src/main.js
- src/store/__tests__/rulers.spec.ts
- src/store/tools/crosshairs.ts
- src/store/tools/index.ts
- src/store/tools/paint.ts
- src/store/tools/rulers.ts
This improves the testing around the tools, as well as makes the API more uniform.
> Improve tools

- src/components/App.vue
- src/components/DataBrowser.vue
- src/components/PaintControls.vue
- src/components/SampleDataBrowser.vue
- src/components/VolumeRendering.vue
- src/composables/useCameraOrientation.ts
- src/config.ts
- src/constants.ts
- src/store/datasets-labelmaps.ts
- src/store/tools/rulers.ts
View and Layout are configuration, so move them to a config file. This indirectly preps for light positioning with CVR.
> Refactor configs

- package-lock.json
- package.json
- src/components/App.vue
- src/components/SaveSession.vue
- src/components/VolumeRendering.vue
- src/io/dicom.ts
- src/io/io.ts
- src/io/state-file/index.ts
- src/io/state-file/schema.ts
- src/io/state-file/utils.ts
- src/io/types.ts
- src/io/zip.ts
- src/store/datasets-dicom.ts
- src/store/datasets-images.ts
- src/store/datasets.ts
This currently saves/restores the datasets and the currently selected dataset.
> feat: Add basic session saving

- package-lock.json
- package.json
- src/components/VolumeRendering.vue
- src/composables/useSceneBuilder.ts
Additionally, reduces the number of unnecessary updates via colorBy.
> fix(VolumeRendering): regression on color range

- src/components/App.vue
- src/components/VtkThreeView.vue
- src/components/VtkTwoView.vue
- src/composables/sync/__tests__/useWindowingSync.spec.ts
- src/composables/sync/useWindowingSync.ts
- src/composables/usePersistCameraConfig.ts
- src/config.ts
- src/io/state-file/index.ts
- src/io/state-file/schema.ts
- src/store/view-configs.ts
- src/store/view-configs/camera.ts
- src/store/view-configs/common.ts
- src/store/view-configs/slicing.ts
- src/store/view-configs/types.ts
- src/store/view-configs/volume-coloring.ts
- src/store/view-configs/windowing.ts
- src/store/views.ts
- src/utils/index.ts
> feat(state): add view config to state file

- src/composables/__tests__/useDoubleRecord.spec.ts
- src/composables/useDoubleRecord.ts
- src/store/datasets-images.ts
> fix: delete guard and arg ordering bugs

- src/components/tools/WindowLevelTool.vue
Also removes old commented code.
> fix(WindowLevelTool): guard against 0 window

- src/components/ToolStrip.vue
- src/components/tools/CrosshairsTool.vue
- src/components/tools/PanTool.vue
- src/components/tools/RulerTool.vue
- src/components/tools/WindowLevelTool.vue
- src/components/tools/ZoomTool.vue
- src/io/state-file/index.ts
- src/io/state-file/schema.ts
- src/io/vtk/async.reader.worker.ts
- src/io/vtk/async.ts
- src/io/vtk/async.writer.worker.ts
- src/io/vtk/common.ts
- src/shims-vtk.d.ts
- src/store/datasets-labelmaps.ts
- src/store/tools/crosshairs.ts
- src/store/tools/index.ts
- src/store/tools/paint.ts
- src/store/tools/rulers.ts
- src/store/tools/types.ts
- src/types/vtk-types.ts
This is branched of #128 which should go in first ...
Closes #114.
> Save and restore tool state

- src/components/VolumeRendering.vue
- src/config.ts
- src/store/datasets-images.ts
- src/store/view-configs.ts
- src/store/view-configs/volume-coloring.ts
This will select a default preset based on the modality. Currently, only CT and MR are supported.
Closes #131 
FYI @aylward @cjh1 @PaulHax
> feat(VolumeRendering): default colors via modality

- src/components/App.vue
- src/components/DataBrowser.vue
- src/components/MessageCenter.vue
- src/components/PatientStudyVolumeBrowser.vue
- src/components/VtkTwoView.vue
- src/store/datasets-dicom.ts
- src/vtk/LPSView3DProxy/index.js
- UI fixes for notifications and thumbnails
- 3D view lighting should be reset
- DICOM data deletion bug fixed
- gracefully handle bad zip files
> Miscellaneous fixes

- src/components/App.vue
- src/components/MessageNotifications.vue
- src/store/__tests__/messages.spec.ts
- src/store/messages.ts
This allows for the loading message to persist instead of disappearing after a timeout.
@cjh1 @PaulHax
> feat(messages): support message persistence

- src/components/App.vue
- src/components/MessageItem.vue
- src/components/PatientStudyVolumeBrowser.vue
- src/composables/useGlobalErrorHook.ts
- src/io/dicom.ts
- src/store/datasets-dicom.ts
- src/store/datasets.ts
- src/store/messages.ts
- Catch errors that bubble up to the window
- improve messages UI
- minor refactoring for types and linting
@cjh1 @PaulHax
> Error handling

- src/components/AboutBox.vue
- src/components/App.vue
Adds a contact link in the about box.
> fix(About): add contact form link

- src/components/VolumeProperties.vue
- src/store/tools/crop.ts
- src/store/view-configs/volume-coloring.ts
- update lights properly and disables flipping the light when using the headlight
- avoids flickering when LAO is enabled
Closes #163
> Improve CVR

- src/components/SampleDataBrowser.vue
- src/components/VolumeProperties.vue
- src/components/tools/crop/CropControls.vue
- remove debugging statement
- force crop controls to be in dark mode
- properly bind CVR controls to switches
> Minor fixes

- public/index.html
- vue.config.js
Tag ID is supplied through netlify environment variables.
> Adds GA support

- src/components/ModulePanel.vue
> fix(ModulePanel): hide AI tab

- package-lock.json
- package.json
- src/components/VtkThreeView.vue
- src/composables/isViewAnimating.ts
- src/composables/useViewProxy.ts
- src/composables/useWidgetManager.ts
This disables CVR while the 3D view is animating. I will also investigate disabling CVR while cropping.
@jadh4v please play with this to see if performance is any better. You can use the netlify link at the bottom of the Github Actions checks.
Closes #195.
> Disable CVR while animating

- src/components/tools/crop/Crop2DLineHandle.vue
- src/components/tools/crop/Crop3D.vue
Closes #192 
Avoids unnecessary updates by checking planes for equality.
@jadh4v
> Improve cropping performance in 2D views

- src/components/App.vue
Add no-cloud icon and message that data stays local on opening screen.
> ENH: Post welcome message that data stays local to machine.

- src/components/VolumeProperties.vue
- src/components/VolumeRendering.vue
- src/composables/useViewProxy.ts
Defers rendering (or disables CVR) when updating rendering parameters.
> Defer input updates

- src/components/DataBrowser.vue
- src/components/PatientBrowser.vue
- src/composables/usePanels.ts
- src/types/views.ts
Close Sample Data panel on data load.
closes #177
The deploy preview test site:
https://deploy-preview-231--volview.netlify.app/
> feat(DataBrowser): expand panel on data load

- src/components/App.vue
Improve wording and spacing of the message on data security
> ENH: Clarify the intro message regarding data never leaving machine.

- src/components/VtkTwoView.vue
- src/components/styles/vtk-view.css
Keys active on mouse hover or focus.
> feat(VtkTwoView): change slice with arrow keys

- src/components/DragAndDrop.vue
This adds support for dragging and dropping of folders on supported platforms.
> Support drag-and-drop of folders

- src/components/AboutBox.vue
This work was funded, in part, by the NIH via NIBIB and NIGMS R01EB021396,
NIBIB R01EB014955, NCI R01CA220681, and NINDS R42NS086295
> ENH: Add funding information to About box.

- public/global.css
- src/components/RenderingModule.vue
- src/config.ts
- Remove scroll bar on right
- Change default MR preset
- Closes #246
> Minor style and default tweaks

- src/components/AboutBox.vue
github.com/kitwaremedical -> github.com/kitware
> DOC: Fix github URL in AboutBox

- patches/vuetify+2.6.10.patch
- src/components/App.vue
- src/components/ResizableNavDrawer.vue
- src/components/SliceSlider.vue
- src/core/tools/paint/index.ts
- src/vtk/PaintWidget/behavior.ts
Some fixes that make touch interaction more feasible.
> Touch fixes

- public/global.css
- src/components/App.vue
- src/components/ModulePanel.vue
- src/components/VolumeRendering.vue
- src/components/VtkTwoView.vue
- src/components/styles/vtk-view.css
- src/main.js
- src/utils/hacks.ts
> More mobile fixes

- documentation/content/doc/loading_data.md
- src/components/App.vue
- src/components/MessageNotificationContent.vue
- src/components/MessageNotifications.vue
- src/composables/useAppLoadingNotifications.ts
- src/constants.ts
- src/utils/index.ts
This adds the ability to load remote datasets via URL parameters.
> Load remote urls

- src/components/App.vue
- src/components/SaveSession.vue
- src/io/state-file/index.ts
If there is a `save` URL parameter and VolView is build with `VUE_APP_ENABLE_REMOTE_SAVE=true`, VolView's "save" button makes a POST request to that URL with the session.zip file.
Example `save` parameter:
`?save=http://localhost:8080/api/v1/item/6425c4b4994364f4d5dcb7b2/volview`
Example build command:
`VUE_APP_ENABLE_REMOTE_SAVE=true npm run build`
> feat(App): save url parameter POSTs session.zip

- src/components/AboutBox.vue
Adds version info for VolView, vtk.js, and itk-wasm at the bottom of the about box.
> feat(AboutBox): add version info

- package-lock.json
- package.json
- Also disables auto-switching to WebGPU.
> Bump VolView to 4.1.0

- package-lock.json
- package.json
> chore: update vtk.js to 27.4.6

- src/components/App.vue
- src/config.ts
Also: make layout view menu stay open after selecting view
Closes #271
> feat: add axial-only view layout

- src/components/tools/WindowLevelTool.vue
Fixes strange update of window width.
Refactored to make vertVal a computed ref, then the manipulator "set" function sets the Pinia store width.
Closes #364
> fix(WindowLevelTool): finicky window width update

- src/components/App.vue
- src/components/SaveSession.vue
Clicking the save session used to close the dialog yeah?
> Close dialog on save

- src/components/AboutBox.vue
> fix(AboutBox): spelling error

- src/components/tools/BoundingRectangle.vue
- src/components/tools/polygon/PolygonWidget2D.vue
> fix(build): Use import type instead of import

- src/vtk/PolygonWidget/behavior.ts
> fix(polygon): fix shift clicking on polygon locks camera pan

- src/components/MeasurementsToolList.vue
Some annotation jobs require a specific number of annotations to be complete.  As a quality assurnace aid, add some text with selected annotation tool counts.
> feat(MeasurementsToolList): add selected annotation count

- src/components/tools/paint/PaintWidget2D.vue
- src/vtk/PaintWidget/behavior.ts
- src/vtk/PolygonWidget/behavior.ts
- fix switching layouts with paint active
- show paint stencil when mouse starts in view 
- fix switching from polygon to paint tool
> Paint and Polygon Tool fixes

- src/components/App.vue
- src/components/CloseableDialog.vue
- src/components/KeyboardShortcuts.vue
- src/components/Settings.vue
- src/composables/actions.ts
- src/config.ts
- src/constants.ts
- src/io/import/processors/handleConfig.ts
- src/store/keyboard-shortcuts.ts
Pressing `?` or clicking button on setting menu pops a modal:
> Keyboard shortcuts cheat-sheet

- package-lock.json
- package.json
- src/vtk/CrosshairsWidget/behavior.ts
- src/vtk/PaintWidget/behavior.ts
- src/vtk/PolygonWidget/behavior.ts
- src/vtk/RulerWidget/behavior.ts
Updates vtk.js to incorporate https://github.com/Kitware/vtk-js/pull/2887.
> feat(vtk.js): upgrade to v28

- src/store/tools/crop.ts
The crop planes should be reoriented to face each other.
Fixes #455
> fix(crop): bad crop planes from negative spacing

- src/io/import/processors/importSingleFile.ts
- src/store/datasets-dicom.ts
> fix(dataset-dicom): throw error if passed file but no volume results

- src/components/VtkThreeView.vue
setGradientOpacityMinimumOpacity -> setGradientOpacityMaximumOpacity
> fix(cinematicRendering): fix copy-and-paste error

- src/components/App.vue
- src/components/WelcomePage.vue
- Refactors out the welcome page to a separate component
- Adds a loading indicator to the welcome page
Closes #495 and partially addresses #365.
> Welcome page loading indicator

- src/components/VolumeProperties.vue
> fix(rendering-ui): move "local ambient occlusion" option

- .github/workflows/e2e.yml
- package-lock.json
- package.json
- src/store/view-configs/volume-coloring.ts
Defaults to standard rendering.
> feat(cvr): default to standard rendering

- src/components/AboutBox.vue
Adds a banner indicating that VolView is for investigational use only.
> feat(AboutBox): add investigation-use only banner

- src/components/LayoutGrid.vue
- src/core/viewTypes.ts
- src/io/state-file/schema.ts
- src/types/views.ts
Extract out the mapping from ViewType to Component to a more readily customizable file.
> feat(config): specify layout component name

- src/components/EditableChipList.vue
> fix(EditableChipList): typo

- src/components/Settings.vue
- src/components/SliceViewer.vue
- src/components/vtk/VtkSliceView.vue
- src/components/vtk/VtkVolumeView.vue
- src/store/view-configs/camera.ts
Related to https://github.com/Kitware/VolView/issues/638
> feat(camera): Add option to disable camera auto reset

- vite.config.ts
> fix: vtk.js version not showing up

- src/actions/loadUserFiles.ts
- src/store/segmentGroups.ts
Also fix trying to get the image name out of the image store after deleting the image from the image store.
> Use DICOM series number to match with image seg files

- src/components/LayoutGrid.vue
- src/store/views.ts
Save the current active view. This feature is necessary to https://github.com/Kitware/VolView/issues/660 and https://github.com/Kitware/VolView/pull/548
> feat(View): Save active view id

- src/components/AnnotationsModule.vue
- src/components/tools/windowing/WindowLevelControls.vue
- src/constants.ts
> Default to Segment Groups under Annotations and Simpify CT Presets

- src/components/AboutBox.vue
Hello! I felt compelled to provide this typo-fix for this small company dear to my heart.
Awesome project, thanks!
:v:
> Fix url typo in AboutBox.vue

- src/io/itk/itkConfig.js
- vite.config.ts
> chore: make base path relative

- server/examples/example_api.py
- server/examples/example_class_api.py
- src/components/ModulePanel.vue
Fixes showing the filtered image and uses JS logic to hide Remote tab.
> Python server maintenance

- src/components/MeasurementsToolList.vue
- src/components/SegmentGroupControls.vue
- src/components/SegmentGroupOpacity.vue
- src/components/SliceViewer.vue
- src/config.ts
- src/store/segmentGroups.ts
- src/store/tools/paint.ts
- src/store/tools/useAnnotationTool.ts
> Batch edit segment groups

- src/components/App.vue
- src/components/vtk/VtkVolumeView.vue
> Image name in document title

- src/components/tools/ScalarProbe.vue
this is an adjustment version for PR https://github.com/Kitware/VolView/pull/722
> Fix vue warning and avoid accessing undefined rep in ScalarProbe.vue

- src/core/streaming/dicomChunkImage.ts
- src/io/dicom.ts
- src/store/segmentGroups.ts
Loading segmentations how happens through the streaming interface.
> fix(seg): regression with loading seg images

- src/config.ts
The prostate and fetus have some overlap to test "add as layer"
> feat(config): change default layer colormap to 2hot-opaque

- src/components/PaintControls.vue
- src/core/tools/paint/index.ts
- src/store/tools/paint.ts
Adds thresholding capabilities to painting.
> feat(paint): thresholding support
