Kitware/VolView

- src/components/VtkTwoView.vue
- src/vtk/CutGeometryRepresentationProxy/index.js
In the event there are no base images, setting the slice for the first
scene source is the correct behavior.
> fix(VtkTwoView): Cut first scene source

- vue.config.js
@floryst I was unable to get the source to load correctly in the debugger. This resolves the issue for me. It would also gives us source maps in production, at the cost of slower rebuild times.
> Switch to 'source-map' source maps

- src/components/ModulePanel.vue
@floryst This removes the arrows unless they are needed. I assume you think we should also recoup the space, which will require a like more work.
> fix: Don't display arrows unless they are needed

- src/components/ModulePanel.vue
For some reason on mobile ( when the width getis small ) the arrows are disabled by default. Override the styling to hidden them when they are disabled.
> Switch to always showing arrows

- src/components/App.vue
- src/store/views.ts
This PR ensures that the layout is added to the store, needed for state export/import. Note that there are some existing vtk.js errors when switching between the two layouts.
> Add layout to store

- src/components/tools/CrosshairsTool.vue
- src/shims-vtk.d.ts
- src/store/tools/crosshairs.ts
Handles the case where the image polydata is actually inflated by 0.5 spacing.
> fix(crosshairs): handle 0.5 inflation

- src/components/tools/SliceScrollTool.vue
This avoids an infinite loop on setSlice when the slicing default is updated.
Also closes #38
> fix(SliceScrollTool): do not watch scrollVal

- src/components/VtkThreeView.vue
The opacity mapping range was being set alongside the colormap mapping range. We only want the colormap mapping range to be updated.
> fix(VtkThreeView): alpha range fixed to data range

- src/components/ToolStrip.vue
- src/components/tools/ManipulatorTool.vue
- src/components/tools/PanTool.vue
- src/components/tools/ZoomTool.vue
- src/shims-vtk.d.ts
- src/store/tools/index.ts
Add buttons for the PanTool and the ZoomTool in the ToolStrip.
When clicked, these tools replace de default interaction (window&level) and
can be used with left click + drag.
> feat(ToolStrip): Add buttons for PanTool and ZoomTool

- src/components/tools/crosshairs/CrosshairSVG2D.vue
- src/components/tools/ruler/RulerSVG2D.vue
- src/core/tools/paint/index.ts
- src/store/tools/rulers.ts
- Ruler and crosshairs were not updating when the window gets resized.
- paint wasn't drawing due to negative slice values
- proper ruler uninitialize cleanup
> fix: update SVG points on container resize

- src/components/App.vue
- src/config.ts
- src/store/views.ts
This fix allows to configure layouts only in the `config.ts` file, without having to modify the `App.vue` template.
> fix(layouts): Make layouts more generic

- src/components/VtkTwoView.vue
- src/composables/sync/__tests__/createPrimitiveSyncContext.spec.ts
- src/composables/sync/__tests__/useWindowingSync.spec.ts
- src/composables/sync/createPrimitiveSyncContext.ts
- src/composables/sync/useWindowingSync.ts
Adds window & level syncing back in at the app level, and not the proxy level (which made it more difficult to track the current window/level properties).
> feat(TwoView): sync windowing parameters

- src/components/AnnotationsModule.vue
- src/components/ImageListCard.vue
- src/components/MeasurementsList.vue
- src/store/tools/rulers.ts
- Ruler annotations now have a jump-to button.
- The ruler list is now filtered by the active image, instead of showing every available ruler.
- Measurements list was not correctly overflowing with a scroll bar.
- The image list card should not flex-wrap when the container width shrinks
Closes #138 
FYI @PaulHax @cjh1 @aylward
> Adds ruler jump-to

- src/components/VtkThreeView.vue
The heuristic for sample distance computation is too conservative
and produced significant speckle noise in the renderings.   This
commit decreases sample distance and image quality become quite good.
> ENH: Improve render quality by descreasing sample distance

- src/components/VolumeRendering.vue
Graph's frame now fits in x and y.  Also removed extra (redundant) padding in x.
> BUG: Remove slider appearing next to transfer func graph

- src/components/VolumeProperties.vue
- src/components/VtkThreeView.vue
- src/io/state-file/schema.ts
- src/store/view-configs/volume-coloring.ts
- src/types/views.ts
When option is enabled, light is a headlight and moves as camera moves.
When disabled, position of light is fixed if the camera is moved.
Allows the user to specify how shadows should be cast.
> ENH: Add option for light to follow camera and otherwise remain fixed

- src/components/App.vue
Prevents the 3D view from unnecessarily rendering when interacting with the 2D views.
Closes #175
> fix(App): remove auto-animation of views

- src/components/App.vue
- src/components/ItemGroup.vue
- src/components/ToolStrip.vue
Adds a separator under the mouse tools for delineation with the annotation tools.
> fix(ToolStrip): add separator under mouse tools

- src/utils/vtk-helpers.ts
This adds an extra guard against potentially unknown presets. (Not sure how it happens.)
Closes #206.
> fix(OpacityWidget): guard against unknown preset

- src/components/PaintControls.vue
- src/core/tools/paint/circle-brush.ts
- src/core/tools/paint/index.ts
- src/store/tools/paint.ts
- src/vtk/PaintBrushContextRepresentation/index.js
Closes #72 
This changes the paint brush behavior to directly map into world space without extra scaling factors.
FYI @PaulHax
> Paint in world space

- src/components/styles/utils.css
- src/components/tools/ManipulatorTool.vue
- src/components/tools/MouseManipulatorTool.vue
- src/components/tools/PanTool.vue
- src/components/tools/ZoomTool.vue
Allow the default mouse actions (panning, zooming) to continue working with modifier keys even when the primary interaction tool (bound to left-mouse click-drag) is changed through the toolbar.
Addresses Issue: https://github.com/KitwareMedical/VolView/issues/172
> fix(ManipulatorTool): retain default mouse action across tools

- src/components/tools/crop/Crop3D.vue
- src/shims-vtk.d.ts
- src/store/datasets-images.ts
This sets the widget bounds, ensuring that the dataset is always centered. Closes #176
> Fix incorrect widget bounds

- src/components/VtkThreeView.vue
- src/components/tools/PanTool.vue
- src/components/tools/ZoomTool.vue
Addresses issue #193
Make mouse interaction consitent across 2D and 3D views.
Fix direction of 2D zooming (to be consistent with 3D zooming).
Add middle click for panning and right click for zooming in 2D.
Add middle click for panning in 3D.
Resulting state of interaction:
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-8687c641-7fff-728c-8696-271cc8fd7575"><div dir="ltr" style="margin-left:0pt;" align="left">
Action | 2D | 3D
-- | -- | --
Left | grayscale | rotate
Mid | (proposed: pan) | (proposed: pan)
Right | (proposed: zoom) | zoom
Ctrl + Left | zoom | zoom
Shift + Left | pan | pan
Wheel | navigate slices | zoom
</div></b>
</body>
</html>
> Consistent 2D/3D mouse interaction

- src/components/App.vue
- src/components/ToolStrip.vue
Group 2D controls (w/L, pan, zoom, crosshairs), annotation tools (paint, ruler), and 3D controls (cropping).   Add divider between each group.
New layout:
| Before | After |
|--|--|
| ![image](https://user-images.githubusercontent.com/219043/202930655-72694acc-4ccf-4709-9c3f-72466e5007b6.png) | ![image](https://user-images.githubusercontent.com/279727/202929980-caf2641e-4f3d-4663-b81a-f411cc08ac78.png) |
> ENH: Change order of tools on toolbar

- .github/workflows/publish.yml
Instead of using `kw-doc` to publish, we use Pages artifacts to achieve the same without pushing to the repo.
> chore(docs): use action for Pages publishing

- src/components/App.vue
- src/components/DragAndDrop.vue
Do not overload the native "drop" event, otherwise it'll trigger twice.
> fix(DragAndDrop): conflict with native drop event

- patches/@kitware+vtk.js+26.5.4.patch
- patches/itk-wasm+1.0.0-b.66.patch
- src/io/dicom.ts
- src/io/itk/itkConfig.js
- vue.config.js
- Testing minor optimizations to a hot loop in vtkOpenGLTexture by reducing the number of object lookups.
- Preloads the `read-dicom-tags` pipeline to avoid multiple fetch calls for the same pipeline when reading in a loop. This is less of a concern for image file readers, but it's still good to note it as a potential issue.
- Restores the stack pointer after every `main()` call, since we do not re-initialize the webworker/emscripten program on every call. Cleans up a stack memory leak. (This makes no assumption on the state of the heap in between main() runs.)
FYI @thewtex @PaulHax the last point above may be a point of discussion for re-using webworkers. Do we continue to treat main() as the entrypoint, or do we instead expose some separate run() function?
> Fixes a stack memory leak and extraneous readDICOMTag XHRs

- vue.config.js
Fixes #286. The default public path should be `/`.
> fix(vue.config): default public path

- src/io/vtk/async.ts
Avoids this error when saving labelmaps:
`Refused to execute script from 'http://localhost:8081/5ccc414e5c4232d9.ts' because its MIME type ('video/mp2t') is not executable.`
> fix(async): use built-in URL api

- src/components/App.vue
- src/components/SampleDataBrowser.vue
- src/io/io.ts
- src/io/manifest.ts
- src/io/state-file/index.ts
- src/io/state-file/schema.ts
- src/io/state-file/utils.ts
- src/io/types.ts
- src/io/zip.ts
- src/store/__tests__/datasets.spec.ts
- src/store/datasets-dicom.ts
- src/store/datasets-files.ts
- src/store/datasets-images.ts
- src/store/datasets-labelmaps.ts
- src/store/datasets.ts
- src/store/dicom-web/dicom-web-store.ts
- src/store/view-configs/common.ts
- src/utils/index.ts
- Loads a `session.volview.zip` state file if in `files` URL parameter.
- Fetch remotely loaded datasets from URLs in state file, rather than zipping in all files.
- Introduce `DatasetFile` type with copyleft `{ url, remoteFilename }` properties.  
- Files downloaded from url parameters, JSON manifest files, and sample datasets get wrapped as a `DatasetFile`.  
- `datasets-dicom` and `datasets-images` eventualy pass `DatasetFile`s to `datasets-files`.
- On Save State: DatasetFiles with `url` and `remoteFilename` are saved as "Remote Datasets" in the JSON manifest and their raw data is not zipped into the state file.  `state-file/utils.ts` does this and is effectively has `datasets-files`' serialize and deserialize functions.
For each scenario, verify:
- Save session has no errors
- Remote …
> Remote state

- src/io/state-file/index.ts
- src/store/datasets-labelmaps.ts
- src/store/datasets.ts
- src/store/tools/index.ts
- src/store/tools/rulers.ts
Label maps and rulers would not load on DICOM files after serialization.  Their serialized representation hold the imageStore ID but datasets are serialized under VolumeKey or ImageID.
Down the line might be good to move to a `DatasetID` generated by `dataset.ts` that annotations, view configs, serialization use no matter the image type.  Or we slowly annotations and serialization to using `DataSelection`
> Fix restore labelmaps and rulers on DICOMS

- src/io/io.ts
- src/store/datasets-files.ts
With nested zip files, the original zip file would get mixed in with the extracted files, resulting in an Error: cannot find reader for .zip
Test file with nested zip.
[zip-in-zip.zip](https://github.com/Kitware/VolView/files/11182269/zip-in-zip.zip)
Also, remove unused and buggy makeZip()
> fix(io): avoid error when loading a zip in a zip

- package-lock.json
- package.json
- src/components/VolumeProperties.vue
- src/components/VtkThreeView.vue
- src/io/state-file/schema.ts
- src/store/view-configs/volume-coloring.ts
- src/types/views.ts
> Volume quality slider

- src/store/view-configs/volume-coloring.ts
Do not use the opacity function's range. Instead, rescale it to the dataset range.
> fix(volume-coloring): opacity range is image range

- src/components/App.vue
- src/core/__tests__/pipeline.spec.ts
- src/core/importDataSources.ts
- src/core/pipeline.ts
- src/io/index.ts
- src/io/io.ts
- src/io/magic.ts
- src/io/manifest.ts
- src/io/mimeTypes.ts
- src/io/readers.ts
- src/io/state-file/index.ts
- src/io/state-file/utils.ts
- src/io/zip.ts
- src/store/datasets-dicom.ts
- src/store/datasets-images.ts
- src/store/datasets.ts
- src/types/index.ts
- src/utils/fetch.ts
- src/utils/path.ts
- Data sources are imported via a flexible pipeline mechanism.
- Files are typed based on mime type rather than extension. Fixes a bug
where we do not handle the OS giving a mimetype in File.type.
- Magic handling and mime types are split out into their own files.
The bulk of the data source loading pipeline resides in `importDataSources.ts`.
> Pipeline data loading

- src/io/dicom.ts
The 'initialize()' method, which was declared with a 'private' qualifier inside the DICOMIO class, is being called from outside and thus the 'private' qualifier is removed.
> fix(io): Remove private qualifier initialize method in DICOMIO Class

- src/core/dicom-web-api.ts
- src/store/dicom-web/dicom-web-store.ts
- Remove trailing slash if on host URL
- Support minimal metadata responses
- Add a `dicomweb=http://localhost:5173/dicom-web` URL parameter to configure default host
> DICOMWeb fixes for Google hosted service

- documentation/content/doc/loading_data.md
- src/core/importDataSources.ts
- src/io/dicom.ts
- src/io/googleCloudStorage.ts
- src/utils/fetch.ts
This adds support for `gs://<bucket>/<object prefix>` URIs. It will download all of the objects with the given object prefix and then attempt to load them.
Todo:
> Support downloading from Google Cloud Storage URIs

- src/components/DataBrowser.vue
- src/components/dicom-web/DicomWebSettings.vue
- src/components/dicom-web/PatientList.vue
- src/core/dicom-web-api.ts
- src/store/dicom-web/dicom-meta-store.ts
- src/store/dicom-web/dicom-web-store.ts
- src/utils/index.ts
Can specify a study or a series on the DICOMWeb server with the URL.
For a study URL like `http://localhost:3000/dicom-web/studies/someid` VolView will show *just* that study in the data browser.
For a series URL like `http://localhost:3000/dicom-web/studies/someid/series/anotherid` VolView will automatically load the series as a volume .
Example url:
https://deploy-preview-327--volview-dev.netlify.app/?dicomweb=https://dicomweb.netlify.app/dicom-web/studies/1.3.6.1.4.1.14519.5.2.1.8421.4009.312603252934799756197864329946/series/1.3.6.1.4.1.14519.5.2.1.8421.4009.216553465756246417429199106507
> DICOMWeb deep addresses

- documentation/content/doc/loading_data.md
- documentation/content/doc/mouse_controls.md
- documentation/content/doc/rendering.md
- documentation/content/doc/state_files.md
- documentation/content/doc/toolbar.md
- documentation/content/doc/welcome_screen.md
Ditches the nice thin title font for standard markdown simplicity.  Fixes title prefix.
Adds DICOMWeb docs
Fixes overflow on URL parameters.
> Doc formatting

- src/components/AboutBox.vue
Add a link in the AboutBox to the VolView community support forum.
Community Support is available in the VolView subcategory in the VTK/Web discourse forum.
* https://discourse.vtk.org/c/web/volview/14
> AboutBox: Add link to discourse category for community support

- src/components/SaveSession.vue
- Saving now shows a loading indicator.
- Prevent refresh when using Enter to save the session.
> fix(SaveSession): loading state and no refresh

- src/components/VtkTwoView.vue
Active Crop tool still kills views after switching view layout.
Fixes #341
> fix(VtkTwoView): conditionally mount tool components

- src/components/VtkTwoView.vue
- src/components/tools/crop/Crop3D.vue
- src/components/tools/crosshairs/CrosshairSVG2D.vue
- src/components/tools/rectangle/RectangleSVG2D.vue
- src/components/tools/ruler/RulerSVG2D.vue
- src/composables/useViewProxy.ts
- src/constants.ts
Crop3D: Avoids calling widgetManger.addWidget before widgetManager is linked to viewProxy
Reverts conditional rendering of 2D tools on useViewProxyMounted.  Applies initialization fix to useViewProxy to avoid adding a widget to widgetManager before linking with viewProxy.
Fixes resize update for SVG widgets by calling ResizeObserver  with tool container DIV rather than SVG group element (which did not trigger ResizeObserver callback.) 
fixes #343
> Fixes for tool widget manager life-cycle and SVG tool resize update

- vite.config.ts
We will stick with 8080, as was the case pre-vite migration.
> chore(vite): dev server on port 8080

- package-lock.json
- package.json
- src/components/LabelControls.vue
- src/components/LabelEditor.vue
- src/components/MeasurementsRectangleList.vue
- src/components/MeasurementsRulerList.vue
- src/components/RectangleControls.vue
- src/components/RulerControls.vue
- src/config.ts
- src/io/import/processors/handleConfig.ts
- src/io/state-file/index.ts
- src/io/state-file/schema.ts
- src/store/__tests__/rulers.spec.ts
- src/store/ids.ts
- src/store/tools/rectangles.ts
- src/store/tools/rulers.ts
- src/store/tools/useAnnotationTool.ts
- src/store/tools/useLabels.ts
- src/types/annotationTool.ts
- src/types/index.ts
- src/utils/index.ts
Adds edit label and add label buttons to label list card:
Clicking the pencil button pops a modal:
closes #347
> Tool Labels: Add, Edit, Delete

- src/components/LabelEditor.vue
Updates the LabelEditor to look like the following screenshot and supports Enter in the label name text editor to close.
> feat(LabelEditor): styles and enter to close

- package-lock.json
- package.json
- src/components/AboutBox.vue
- src/components/App.vue
- src/components/CloseableDialog.vue
- src/components/LabelControls.vue
- src/components/LabelEditor.vue
- src/components/MessageCenter.vue
- src/components/SaveSession.vue
- src/components/Settings.vue
- src/components/VtkThreeView.vue
- src/components/tools/PanTool.vue
- src/components/tools/WindowLevelTool.vue
- src/components/tools/ZoomTool.vue
- src/constants.ts
- src/global.css
This unifies how we size and use closeable dialogs.
- defaults for how dialogs are sized on mobile and desktop
- close button is "stickied" to the corner for scrollable content (e.g. the about info dialog)
Other notable changes:
- upgrade to vue 3.3.4. This changed some of the type inference, so the upgrade commit contains those changes.
> Closeable dialogs

- .gitignore
- index.html
- netlify.toml
- netlify/edge-functions/visits.ts
- package-lock.json
- package.json
- src/components/App.vue
- src/components/DataSecurityBox.vue
- src/components/Settings.vue
- src/global.css
- src/utils/errorReporting.ts
- vite.config.ts
- Add more info on how we handle data privacy and security
- Add support for toggling error reporting
- Switch from GA to server side analytics to just track hits
- Remove sentry Replay and performance for now. Enabling Replay requires more testing to ensure we don't send any traces that may reveal info about a user's data
- UX: do not negate the meaning of a toggle. The "Disable error reporting" toggle in the settings now reads "Error reporting", with the toggle state indicating the on/off state.
> Data privacy and security handling updates

- src/components/DataBrowser.vue
- src/io/import/processors/handleConfig.ts
- src/store/data-browser.ts
Kind of silly to make a new store just for this? 🤷  Simpler way?
Closes #380
> feat(DataBrowser): hide Sample Data if configured

- src/components/DataBrowser.vue
- src/components/dicom-web/PatientDetails.vue
- src/components/dicom-web/PatientList.vue
- src/components/dicom-web/StudyVolumeDicomWeb.vue
- src/store/dicom-web/dicom-web-store.ts
UX fixes for DICOMWeb feature
* Even if DICOMWeb host was configured, its panel in the DataBrowser was minimized.  Fixed
* Fix quick showing of "No patients found message" upon initial querying of DICOMWeb server.
* Fix saving URL parameter or env variable to DICOMWeb host local storage key.  Was strange to still have a host configured after removing the URL parameter.
* If deep linking to study/series, expand panels in DataBrowser.  Patient and study sections were minimized until clicked on before.
> UX DICOMWeb fixes

- src/components/DataBrowser.vue
- src/components/dicom-web/DicomWebSettings.vue
- src/components/dicom-web/PatientList.vue
- src/components/dicom-web/StudyVolumeDicomWeb.vue
- src/store/dicom-web/dicom-web-store.ts
* Stops unending spinner on volume thumbnail if error downloading volume
* Editing the host in the settings panel now saves the host to localStorage.
* Editing the host in the settings panel fetched all the studies *twice* if host started not configured.
* DICOMWeb panel now expands when host is configured from settings.
> DICOMWeb fixes

- documentation/content/doc/toolbar.md
- src/components/tools/polygon/PolygonWidget2D.vue
- src/vtk/PolygonWidget/behavior.ts
- src/vtk/PolygonWidget/index.d.ts
- src/vtk/PolygonWidget/state.ts
After finish a polygon with the `Enter` key or double clicking the left mouse button.
Closes #389
> feat(polygon): add enter and double click to finish shortcuts

- src/components/App.vue
Addresses #363
This adds a user feedback button to the vertical toolbar.
@aylward At the moment, it's using a mailto link. We would ideally switch to a form before we merge.
> Add user feedback button

- src/components/LabelmapList.vue
- src/components/MeasurementsRulerList.vue
- src/components/MeasurementsToolList.vue
- src/components/tools/AnnotationContextMenu.vue
- src/components/tools/polygon/PolygonTool.vue
- src/components/tools/polygon/PolygonWidget2D.vue
- src/components/tools/rectangle/RectangleTool.vue
- src/components/tools/rectangle/RectangleWidget2D.vue
- src/components/tools/ruler/RulerTool.vue
- src/components/tools/ruler/RulerWidget2D.vue
- src/composables/annotationTool.ts
- src/store/__tests__/rulers.spec.ts
- src/store/tools/useAnnotationTool.ts
- src/types/annotation-tool.ts
- src/types/polygon.ts
- src/vtk/PolygonWidget/index.d.ts
- src/vtk/PolygonWidget/state.ts
- src/vtk/RulerWidget/index.d.ts
- src/vtk/ToolWidgetUtils/utils.ts
Adds an eyeball button in the MeasurmentToolList to toggle `hidden` state of annotation tools. 
Also adds "Hide" option to right click context menu on annotations.
> Annotation Tool Visibility Button

- .github/workflows/e2e.yml
The windows test is flaky and requires some more investigation. In the meantime, we won't test on windows.
> chore(github): no E2E testing on windows

- src/components/CurrentImageProvider.vue
- src/components/LayoutGrid.vue
- src/components/VtkTwoView.vue
- src/components/tools/SliceScrollTool.vue
- src/composables/useCurrentImage.ts
- src/composables/usePersistCameraConfig.ts
- src/composables/useSceneBuilder.ts
- src/store/tools/crop.ts
- src/store/tools/paint.ts
Adds a CurrentImageProvider, which allows for changing the return value of the `useCurrentImage()` composable.
> Current image provider

- src/components/ToolStrip.vue
- src/components/tools/AnnotationContextMenu.vue
- src/components/tools/AnnotationInfo.vue
- src/components/tools/BoundingRectangle.vue
- src/components/tools/polygon/PolygonSVG2D.vue
- src/components/tools/polygon/PolygonTool.vue
- src/components/tools/polygon/PolygonWidget2D.vue
- src/components/tools/rectangle/RectangleSVG2D.vue
- src/components/tools/rectangle/RectangleTool.vue
- src/components/tools/rectangle/RectangleWidget2D.vue
- src/components/tools/ruler/RulerSVG2D.vue
- src/components/tools/ruler/RulerTool.vue
- src/components/tools/ruler/RulerWidget2D.vue
- src/composables/annotationTool.ts
- src/composables/usePopperState.ts
- src/constants.ts
- src/store/tools/types.ts
- src/vtk/PolygonWidget/behavior.ts
- src/vtk/PolygonWidget/state.ts
- src/vtk/RectangleWidget/RectangleLineRepresentation.js
- src/vtk/RectangleWidget/index.js
- src/vtk/RulerWidget/behavior.ts
- src/vtk/RulerWidget/index.js
- src/vtk/ToolWidgetUtils/pointState.js
- src/vtk/ToolWidgetUtils/utils.ts
Hover popup appears 250ms after cursor rests on invisible vtkWidgetRepresentation.
Current look:
Old look:
> Annotation Tool Hover

- src/components/MeasurementsToolList.vue
- src/components/tools/polygon/PolygonSVG2D.vue
- src/components/tools/polygon/PolygonTool.vue
- src/components/tools/polygon/PolygonWidget2D.vue
- src/components/tools/rectangle/RectangleTool.vue
- src/components/tools/rectangle/RectangleWidget2D.vue
- src/components/tools/ruler/RulerTool.vue
- src/components/tools/ruler/RulerWidget2D.vue
- src/composables/annotationTool.ts
- src/composables/useFrameOfReference.ts
- src/store/tools/polygons.ts
- src/store/tools/useAnnotationTool.ts
- src/types/polygon.ts
- src/vtk/ToolWidgetUtils/pointState.js
- src/vtk/ToolWidgetUtils/utils.ts
- Some code refactoring for easier usage
- useFrameOfReference encapsulates the frame of reference handling
- usePlacingAnnotationTool provides a more readable API for managing the placing tool
- added finishedTools to all annotation tools
- simplified the point visibility code to make it more obvious as to what it's doing
- removed the movePoint state from the polygon store
> Simplify tool code

- src/components/tools/polygon/PolygonWidget2D.vue
- src/components/tools/rectangle/RectangleWidget2D.vue
- src/components/tools/ruler/RulerWidget2D.vue
- src/composables/annotationTool.ts
- src/composables/useViewProxy.ts
Fixes #424. The views weren't requesting a render after layout changes. I also created a `useWidgetVisibility` composable to encapsulate this behavior.
I also cleaned up toolId prop usage by directly using the prop and typing the toolId to be `PropType<ToolID>`.
> Fix widgets not rendering after relayout

- src/components/tools/crop/Crop3D.vue
- src/components/tools/polygon/PolygonWidget2D.vue
- src/components/tools/rectangle/RectangleWidget2D.vue
- src/components/tools/ruler/RulerWidget2D.vue
- src/composables/annotationTool.ts
- src/composables/useViewProxy.ts
- src/composables/useWidgetManager.ts
- src/vtk/PolygonWidget/index.d.ts
- src/vtk/RulerWidget/index.d.ts
- src/vtk/ToolWidgetUtils/pointState.js
- src/vtk/ToolWidgetUtils/utils.ts
Three minor refactors:
- getOrigin() in pointState should use toRaw to reduce access overhead. getOrigin() usage should be considered readonly for the most part anyways, since in-place mutation isn't expected to trigger modified().
- Creation of a point state interface for all point-based annotation tools.
- `useViewProxy<Mounted|Unmounted>` has been renamed to `onViewProxy<Mounted|Unmounted>` for more consistent naming. They also now take `MaybeRef<Maybe<ViewProxy>>` instead of requiring the existence of the view proxy.
> Some refactors and cleanups

- src/components/AnnotationsModule.vue
- src/components/LabelControls.vue
- src/components/LabelEditor.vue
- src/components/MeasurementRulerDetails.vue
- src/components/MeasurementToolDetails.vue
- src/components/MeasurementsToolList.vue
- src/components/tools/AnnotationContextMenu.vue
- src/components/tools/AnnotationInfo.vue
- src/components/tools/polygon/PolygonWidget2D.vue
- src/components/tools/rectangle/RectangleWidget2D.vue
- src/components/tools/ruler/RulerWidget2D.vue
- src/composables/annotationTool.ts
- src/io/state-file/schema.ts
- src/store/__tests__/rulers.spec.ts
- src/store/tools/polygons.ts
- src/store/tools/rectangles.ts
- src/store/tools/useAnnotationTool.ts
- src/types/annotation-tool.ts
- src/types/polygon.ts
- src/types/rectangle.ts
- src/types/ruler.ts
The per-tool nominal types weren't proving useful. We now unify all tools to use the same ToolID type.
> refactor: drop tool-specific ID types

- CONTRIBUTING.md
Adds documentation to `CONTRIBUTING.md` with instructions on how to use a local development branch of VTK.js in a local VolView development build.
Also resolves observed type import error when developing against a local VTK.js development branch:
```sh
ERROR  Error: The following dependencies are imported but could not be resolved:                             16:46:24
@kitware/vtk.js/types (imported by C:/repos/VolView/src/components/tools/polygon/PolygonWidget2D.vue?id=0)
Are they installed?
at file:///C:/repos/VolView/node_modules/vite/dist/node/chunks/dep-df561101.js:45705:23
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async file:///C:/repos/VolView/node_modules/vite/dist/node/chunks/dep-df561101.js:45114:38
```
> doc(contributing): Update CONTRIBUTING.md for VTK.js development

- src/components/SampleDataBrowser.vue
- src/config.ts
- src/store/view-configs/volume-coloring.ts
- src/types/index.ts
Adds support for setting volume-coloring defaults. This same API should exist for the other view-config stores eventually.
Sets the default color preset for the fetal sample dataset to US-Fetal.
Fixes #371
> feat(coloring): support config defaults

- src/composables/actions.ts
- src/composables/useKeyboardShortcuts.ts
- src/config.ts
- src/constants.ts
- src/io/import/processors/handleConfig.ts
- src/utils/index.ts
Default key mappings in `config.ts`.  Can change keys in config.JSON.   
Related #390
> Keyboard Shortcuts / Hotkeys

- src/components/tools/BoundingRectangle.vue
- src/components/tools/crosshairs/CrosshairSVG2D.vue
- src/components/tools/polygon/PolygonSVG2D.vue
- src/components/tools/rectangle/RectangleSVG2D.vue
- src/components/tools/ruler/RulerSVG2D.vue
- src/constants.ts
- src/vtk/ToolWidgetUtils/pointState.js
No need to scale SVG circle radius by devicePixelRatio.
Before with devicePixelRatio 1
Before with devicePixelRatio 2
After with devicePixelRatio 1
After with devicePixelRatio 2
> fix(annotation-tools): handle radius too small with devicePixelRatio

- src/components/VtkTwoView.vue
- src/store/view-configs/layers.ts
Removes voxel intensity based opacity transfer for layer slices.  All layer voxels have opacity transfer function Y value of 1.  Layer opacity controled by slice mesh opacity.
Good CT-PT dataset for testing https://demo.orthanc-server.com/app/explorer.html#study?uuid=6b9e19d9-62094390-5f9ddb01-4a191ae7-9766b715
Closes #355
> fix(VtkTwoView): layer opacity has uniform 1 opacity transfer function 

- src/vtk/PaintWidget/behavior.ts
- src/vtk/PolygonWidget/behavior.ts
- src/vtk/RulerWidget/behavior.ts
- src/vtk/ToolWidgetUtils/utils.ts
Seems that Paint is hurting too...
> fix(ruler): avoid error when manipulator returns no worldCoords

- src/components/LayerProperties.vue
- src/components/VtkTwoView.vue
- src/store/view-configs/layers.ts
If configured for axial only view, then add a layer, layer properties GUI would just try to get first view config (Sagittal?), which did not exist.
If a layer was created, without the view mounted, the colorBy layer config would not be set, and the layer would be invisible.
> fix(layers): fix initialization bugs when less than all views mounted

- src/components/tools/windowing/WindowLevelTool.vue
> fix(WindowLevelTool): Do not reset the auto/preset selection

- src/components/LayerList.vue
- src/components/LayerProperties.vue
- src/components/PatientStudyVolumeBrowser.vue
- src/store/datasets-dicom.ts
- src/store/datasets.ts
* Long layer names were squishing the opacity slider horizontally to nothing.
* For DICOM sourced layers, use datasets-image name for layer name.
Will address #462 when this change lands:
https://github.com/Kitware/VolView/pull/444/files#diff-2e48f469094ddae541596589e83ce73d782a438463fffc512e952d1aedd57b73L361-R372
> fix(LayerProperties): handle long layer names

- src/components/AnnotationsModule.vue
- src/components/SegmentGroupControls.vue
- src/components/SegmentList.vue
- src/components/VtkTwoView.vue
- src/composables/useSceneBuilder.ts
- src/config.ts
- src/constants.ts
- src/io/import/processors/restoreStateFile.ts
- src/io/state-file/index.ts
- src/io/state-file/schema.ts
- src/store/segmentGroups.ts
- src/store/tools/index.ts
- src/store/tools/paint.ts
- src/types/segment.ts
- src/vtk/LabelMap/index.d.ts
@aylward @PaulHax this goes into #444. It renames labelmap -> segment group and label -> segment (mask).
> refactor: rename labelmaps to segment groups

- src/components/MessageItem.vue
- src/composables/useGlobalErrorHook.ts
- src/composables/useResizeObserver.ts
- Allow selection of text in the message list
- completely disconnect the ResizeObserver on unmount
- Log out global errors and use a fallback message for error reporting
> Miscellaneous fixes

- src/io/mimeTypes.ts
Fixes #500
Windows uses the non-standard `application/x-zip-compressed` mime type when opening zip files via the file picker. Other platforms (and even drag-and-drop on Windows) uses `application/zip`.
This change adds `application/x-zip-compressed` as a supported mime type.
> fix(mimeTypes): handle windows zip mime type

- package-lock.json
- package.json
- src/components/App.vue
- src/core/remote/client.ts
- src/io/amazonS3.ts
- src/io/googleCloudStorage.ts
- src/utils/__tests__/url.spec.ts
- src/utils/fetch.ts
- src/utils/index.ts
- src/utils/url.ts
whatwg-url parses correctly, but is quite a big dependency. This adds a parseUrl() that only handles Chrome+Firefox quirks regarding parsing of urls using non-special schemes.
> Drop whatwg-url

- src/components/VolumeRendering.vue
- src/components/VtkThreeView.vue
- src/components/VtkTwoView.vue
- src/io/state-file/schema.ts
- src/types/views.ts
- src/utils/vtk-helpers.ts
- src/vtk/PiecewiseWidget/index.js
Vertical shift is allowed when holding control and left-click+dragging up/down. Shifting the points changes opacity.
Initial pass at fixing #188
> feat(vtkPiecewiseWidget): Support vertical movement of points

- src/components/DataSecurityBox.vue
- src/composables/useGlobalErrorHook.ts
- Adds a call to captureException on global errors
- Fixes reportingEnabled not being reactive
> Report global errors

- src/components/tools/paint/PaintWidget2D.vue
- src/store/tools/index.ts
- src/store/tools/paint.ts
Small paint tool fixes:
- If session.volview.zip is loaded with the paint tool initially selected, clicking on the image did not paint.
- If paint tool is activated when mouse is within a view, the stencil shape would not be correct.
> Paint tool on startup fixes

- src/composables/useWebGLWatchdog.ts
- src/utils/errorReporting.ts
- src/utils/gpuInfo.ts
Add extra reporting handlers for webgl context losses and attach GPU information to all reported errors.
> Improved error reporting

- src/utils/errorReporting.ts
- src/utils/gpuInfo.ts
Some platforms (e.g. safari) support OffscreenCanvas but do not support webgl2 with OffscreenCanvas.
> fix(gpuInfo): better fallback logic

- src/components/DragAndDrop.vue
getAsEntry() may return null if the DataTransferItem is not a file.
> fix(DragAndDrop): handle null files

- src/composables/useWebGLWatchdog.ts
The WebGL event is not an exception, just an event object.
> fix(useWebGLWatchdog): just report message

- src/components/tools/crosshairs/CrosshairsWidget2D.vue
- src/components/tools/paint/PaintWidget2D.vue
Could not create widget if View Proxy was not yet created.
Reproduce steps:
1. Activate crosshairs
2. Change view layout
> fix(CrosshairsWidget2D): avoid error when changing layout

- src/components/App.vue
Addresses: https://github.com/Kitware/VolView/issues/519
Show the "toggle sidebar" button by default on all platforms. Earlier it was only enabled for mobile devices. Showing the button on all platforms will enable the user to explicitly show/hide the sidebar as desired.
> fix(sidebar): show toggle sidebar button by default

- src/components/ImageDataBrowser.vue
- src/components/SegmentGroupControls.vue
Convert a loaded image into a labelmap / segment group.
Choosing this option will remove the image from the list of loaded datasets, and create a new segment group under annotations tab using the image as a segmentation/labelmap.
This operation can fail if the segmentation image does not match the bounds of the selected primary image (base image on which the segmentation is to be applied).
WIP, additional points that need fixing:
> Convert a loaded image to segment group

- src/components/CurrentImageProvider.vue
- src/components/VtkObliqueView.vue
- src/components/VtkTwoView.vue
- src/components/tools/SliceScrollTool.vue
- src/composables/annotationTool.ts
- src/composables/useCurrentImage.ts
- src/composables/usePersistCameraConfig.ts
- src/composables/useSceneBuilder.ts
- src/store/datasets.ts
- src/store/tools/crop.ts
- src/store/tools/paint.ts
- src/store/tools/useAnnotationTool.ts
The `CurrentImageProvider` component can now override the image returned from `useCurrentImage()` for a given subtree. The fallback behavior is to use the current global selected image.
This revives #410 with the fallback behavior.
> Support overriding the current image

- src/components/App.vue
Fix the following error when urlParams are empty.
```js
App.vue:206 Uncaught TypeError: Cannot read properties of undefined (reading 'toString')
at setup (App.vue:206:54)
at callWithErrorHandling (chunk-G4DFXOZZ.js?v=fae193fd:1565:18)
at setupStatefulComponent (chunk-G4DFXOZZ.js?v=fae193fd:8631:25)
at setupComponent (chunk-G4DFXOZZ.js?v=fae193fd:8592:36)
at mountComponent (chunk-G4DFXOZZ.js?v=fae193fd:6997:7)
at processComponent (chunk-G4DFXOZZ.js?v=fae193fd:6963:9)
at patch (chunk-G4DFXOZZ.js?v=fae193fd:6436:11)
at render2 (chunk-G4DFXOZZ.js?v=fae193fd:7730:7)
at mount (chunk-G4DFXOZZ.js?v=fae193fd:5215:13)
at app.mount (chunk-G4DFXOZZ.js?v=fae193fd:10537:19)
```
> fix(urlParams): empty save param issue

- src/composables/useCurrentImage.ts
- getImageMetadata: return defaults if no image ID or if imageID is nonexistent, since the method signature doesn't return null.
- Make sure getImageData's return signature only returns null.
> fix(useCurrentImage): return defaults/null

- src/components/LabelControls.vue
- src/components/LabelEditor.vue
- src/components/SegmentEditor.vue
- src/components/SegmentList.vue
- src/components/ToolLabelEditor.vue
- src/io/import/configJson.ts
- src/store/tools/useAnnotationTool.ts
- src/store/tools/useLabels.ts
Warns if user is editing label name and it maches existing label.  "Done" is disabled if name already exists.
Also
* New labels are created with unique names suffixed with a number.
* New labels loop through the confgi.ts:TOOL_COLORS.
* Max width on label editor dialog.
Closes #477
> Label name uniqueness tweeks

- src/components/App.vue
Avoid dropping JSON or array query param arguments on the "save" query parameter by parsing query params without casting to native types in vtkURLExtract.
Now save parameter could be
`/api/v1/folder/65e1f44870447d7525ac0c49/volview?metadata={"linkedResources":{"items":["65e1f4ec70447d7525ac0c54"]}}`
> fix(App): keep query params on save url query param

- src/io/import/importDataSources.ts
- src/store/datasets-layers.ts
- src/store/load-data.ts
The "base" DICOM modalties: 'CT', 'MR', 'DX', 'US'
Side effect: When an image and DICOM are loaded at same time, DICOM is always Primary Selection.
PR does not change Sample Data and DICOMWeb behavior (which only load single volumes at a time at the moment.)
Related issue: #566
> Prefer some DICOMs modalities as primary selection and layer a PET on a CT if it exists

- src/components/tools/windowing/WindowLevelControls.vue
- src/composables/useWindowingConfigInitializer.ts
- src/store/datasets-dicom.ts
Attached DICOM was freezing app.
[1-001.zip](https://github.com/Kitware/VolView/files/14968696/1-001.zip)
> fix(windowing): more robust loading of multi-component DICOMs

- documentation/content/doc/configuration_file.md
- package-lock.json
- package.json
- src/actions/loadUserFiles.ts
- src/io/import/configJson.ts
- src/store/datasets-layers.ts
- src/store/load-data.ts
- src/store/segmentGroups.ts
When loading files, VolView can automatically convert images to segment groups
if they follow a naming convention. For example, an image with name like `foo.segmentation.bar`
will be converted to a segment group for a base image named like `foo.baz`.  
The `segmentation` extension is defined by the `io.segmentGroupExtension` key, which takes a
string. Files `foo.[segmentGroupExtension].bar` will be automatilly converted to segment groups for a base image named `foo.baz`. The default is `''` and will disable the feature.
This config.json will define `myFile.seg.nrrd` as a segment group for a `myFile.nii` base file.
```json
{
"io": {
"segmentGroupExtension": "seg"
}
}
```
Zip with config-auto-seg.json, 3DUS-Fetus.nrrd, and 3DUS-Fetus.0.segmentation.nrrd …
> Auto Segment Group by name

- src/components/tools/polygon/PolygonSVG2D.vue
- src/components/tools/polygon/PolygonWidget2D.vue
- src/utils/frameOfReference.ts
- src/vtk/PolygonWidget/behavior.ts
- src/vtk/PolygonWidget/decimate.ts
- src/vtk/PolygonWidget/index.d.ts
- src/vtk/PolygonWidget/state.ts
Hold left mouse button down to keep dropping points.  Optimizes point count after polygon is "placed."
> Freehand point dropping for Polygon Tool

- src/components/SliceViewer.vue
- src/components/VolumeRendering.vue
- src/components/VolumeViewer.vue
- src/composables/useWindowingConfigInitializer.ts
> fix: apply reset views button to slices and volume views

- src/components/DataBrowser.vue
- src/components/DicomQuickInfoButton.vue
- src/components/ImageDataBrowser.vue
- src/components/LayerProperties.vue
- src/components/PatientBrowser.vue
- src/components/PatientStudyVolumeBrowser.vue
- src/components/SampleDataBrowser.vue
- src/components/SliceViewer.vue
- src/components/VolumeViewer.vue
- src/components/tools/windowing/WindowLevelControls.vue
- src/composables/useCurrentImage.ts
- src/composables/useSliceConfigInitializer.ts
- src/composables/useVolumeColoringInitializer.ts
- src/composables/useWindowingConfigInitializer.ts
- src/io/import/importDataSources.ts
- src/io/import/processors/restoreStateFile.ts
- src/io/state-file/index.ts
- src/io/state-file/schema.ts
- src/store/datasets-dicom.ts
- src/store/datasets-images.ts
- src/store/datasets-layers.ts
- src/store/datasets.ts
- src/store/segmentGroups.ts
- src/store/tools/useAnnotationTool.ts
- src/store/view-configs/layers.ts
- src/store/view-configs/volume-coloring.ts
- src/utils/dataSelection.ts
Volume keys are now used as image data IDs. This simplifies going back and forth between the image and dicom store, and simplifies the structure of the selection object to be just an ID string.
This doesn't address migration of older session files. That is a nice-to-have, but we don't have a good way of handling migrations at the moment. @PaulHax if this breaks stored session files, then I'll add a migration path.
> feat: unify data IDs

- package-lock.json
- package.json
- patches/@velipso+polybool+1.1.0.patch
- src/components/SliceViewer.vue
- src/components/tools/AnnotationContextMenu.vue
- src/components/tools/polygon/PolygonTool.vue
- src/composables/actions.ts
- src/config.ts
- src/constants.ts
- src/store/tools/polygons.ts
- src/utils/frameOfReference.ts
- src/vtk/PolygonWidget/behavior.ts
Right click to merge selected polygons.
Adds a new deprendency `polybool` =/
closes #614
> Merge polygons

- src/components/DataBrowser.vue
Dynamic number of panels with v-model='panels' has an error when removing a panel.
Steps: When I load the prostate, click checkbox to "select all studies," then "delete selected" -> seeing errors [Vue warn]: Unhandled error during execution of beforeUnmount hook and Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'value') at group.ts:338:59
I did not reproduce the error in the Vuetify playground, so not sure how to complain:
[playground](https://play.vuetifyjs.com/#eNqVVk1v2zgQ/SuEdgHJqCXF6e7Fm6RJt5feFthgL3GBKiIds6EogqTUBIb/+z5StCXZauP60Ebz8WbmzQzJh21kdJnfKZW1DYuW0ZUpNVeWGGYbdbOShPBK1dqSLdFsTXZkreuKxDCOV9Kpy1oai38bacm1s0kuZiONZoVlny2roE4st4LNyaYw/xWiYRBZ3bAZub4hydY5IR5ddnBZ60zevZt38s61+xvQlkm7JHEcJN522QN/IP9azeVTMoCakSVpJGVrLhn1frtRqhxJmlDEQ593Et/Fs/mgkCT+eCz4 …
> fix(vuetify): add patch for expandable panels with v-model

- src/composables/actions.ts
- src/composables/useKeyboardShortcuts.ts
- src/config.ts
Support characters like '?' and uppercase letters for keyboard shortcuts.
> fix(useKeyboardShortcuts): allow for shift key plus special characters

- src/store/datasets-dicom.ts
If the VolumeInfo doesn't actually have any windowing information, then treat it as a missing tag.
> fix(dicom): handle missing w/l tags

- src/components/EditableChipList.vue
- src/store/datasets-layers.ts
Fixes auto layering and the label buttons
> Fix label button layout and Layering

- src/composables/untilLoaded.ts
- src/store/datasets-layers.ts
- src/store/segmentGroups.ts
- src/utils/allocateImageFromChunks.ts
- wait for full load of SEG DICOM before resampling to parent.
- Follow ITK Z spacing computation [method](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/IO/ImageBase/include/itkImageSeriesReader.hxx#L211).  ITK takes diff between first and last slice, not first and second.  Produces slightly different spacing for https://data.kitware.com/#item/66be32b7f87a980650f42292
- Unresolved: SEG DICOM hides ImagePositionPatient tag nested under another tag.  This in progress ITK-WASM pipeline would spit out nested tags: https://github.com/InsightSoftwareConsortium/ITK-Wasm/pull/1197
> DICOM Seg fixes

- src/components/ImageDataBrowser.vue
- src/components/Settings.vue
- src/components/SliceViewer.vue
- src/components/vtk/VtkSliceView.vue
- src/components/vtk/VtkVolumeView.vue
- src/composables/usePersistCameraConfig.ts
- src/composables/useSliceConfig.ts
- src/io/import/processors/importSingleFile.ts
- src/io/state-file/schema.ts
- src/store/datasets-images.ts
- src/store/view-configs/camera.ts
- src/store/view-configs/slicing.ts
- src/store/view-configs/types.ts
> Synchronize cameras images

- src/components/tools/crop/Crop3D.vue
- src/components/tools/crop/CropTool.vue
- src/composables/wheneverImageLoaded.ts
Cropping was failing on DICOM images because cropping was initialized before the DICOM data was fully loaded.
> fix(crop): wait for DICOM image load

- src/components/EditableChipList.vue
- src/components/SegmentGroupControls.vue
- src/components/SegmentGroupOpacity.vue
- src/components/SegmentList.vue
- src/components/vtk/VtkSegmentationSliceRepresentation.vue
- src/config.ts
- src/io/state-file/schema.ts
- src/store/segmentGroups.ts
- src/store/tools/paint.ts
- src/types/segment.ts
> Segments:  opacity slider and visibile toggle

- src/io/import/processors/updateFileMimeType.ts
Closes #663, and maybe #655.
Overwrites/normalizes the default OS-provided mimetype. Also ensures that the mime type is a supported mime type.
@PaulHax I think this should be fine, since if it's an unsupported mime type, setting to "null" won't change any logic. 
Should also be applied here: https://github.com/Kitware/VolView/pull/635/files#diff-7d267f00b6c6e1caa0952df237d876fce197c2048228c5f5bda7dd583232a40eR10
> fix(updateFileMimeType): overwrite mimetype

- src/components/PatientStudyVolumeBrowser.vue
> fix(PatientStudyVolumeBrowser): show modality if thumbnail fails

- src/global.css
> feat(global.css): increase tooltip background opacity

- tests/specs/layers.e2e.ts
- wdio.shared.conf.ts
> chore(ci): increase timeouts for flakey e2e tests

- package-lock.json
- package.json
- src/components/SegmentEditor.vue
- src/components/SegmentGroupControls.vue
- src/components/SegmentGroupOpacity.vue
- src/components/SegmentList.vue
- src/components/vtk/VtkLayerSliceRepresentation.vue
- src/components/vtk/VtkSegmentationSliceRepresentation.vue
- src/composables/useSegmentGroupConfigInitializer.ts
- src/io/state-file/schema.ts
- src/store/segmentGroups.ts
- src/store/view-configs/common.ts
- src/store/view-configs/segmentGroups.ts
- src/store/view-configs/types.ts
> Outline segment group rendering

- src/composables/useWindowingConfigInitializer.ts
- src/io/import/configJson.ts
- src/store/view-configs/windowing.ts
Example config:
```json
{
"windowing": {
"width": 50,
"level": 128
}
}
```
> feat(windowing): add forced window/level to JSON config

- src/components/AboutBox.vue
- src/components/App.vue
- src/components/ControlsModal.vue
- src/components/Settings.vue
- src/constants.ts
- Added mouse view controls at top of controls modal.
- Added show control modal button on info modal.
- Moved show controls modal button higher on setting modal.
> feat(ControlsModal): list mouse view controls

- src/components/vtk/VtkSliceViewSlicingManipulator.vue
- src/composables/actions.ts
- src/config.ts
- src/constants.ts
This needs this PR to be merged first: https://github.com/Kitware/VolView/pull/676
> feat(Slice): Use keyboard to change slices of the active view

- docs/.vitepress/config.ts
- docs/authentication.md
- docs/building_for_production.md
- docs/cors.md
- docs/deploying_volview.md
- docs/deployment_overview.md
- package-lock.json
- package.json
- src/components/App.vue
- src/core/dicom-web-api.ts
- src/store/remote-save-state.ts
- src/utils/fetch.ts
- src/utils/index.ts
- src/utils/token.ts
- Adds token and tokenUrl support for obtaining authorization tokens. Tokens are currently sent with same-origin semantics for now.
- Add initial deployment docs
Closes #689
> Authz token in url + initial deployment docs

- docs/.vitepress/config.ts
- docs/authentication.md
- docs/cors.md
- Add CORS note to tokenUrl
- Rename doc to "Authentication & Authorization"
> docs: add CORS note to tokenUrl

- docs/mouse_controls.md
- src/components/App.vue
- src/composables/actions.ts
- src/config.ts
- src/constants.ts
- src/store/datasets.ts
> Delete image shortcut

- .github/workflows/checks.yml
- .github/workflows/publish.yml
ubuntu-20.04 is EOL and is no longer supported by github runners.
> chore(github): use ubuntu-latest

- src/core/streaming/requestPool.ts
This just bumps up the request pool size to ensure we saturate the browser-level number of outgoing requests.
> fix(requestPool): increase pool size

- src/composables/wheneverImageLoaded.ts
closes #721 (hopefully)
The CT-Neck to Prostate switching worked OK for me.  Switching between Prostate and Fetus had cropping issues for me.  This PR fixes Prostate/Fetus case and hoefully gets the CT-Neck/Prostate in the issue.
The bug is that the current implementation of wheneverImageLoaded only watches a derived boolean (hasImageData) that only toggles when the image goes from not-loaded to loaded. If the imageId changes from one valid ID to another (with both returning true), the callback never fires.
> fix(wheneverImageLoaded): run callback when switching images

- src/actions/loadUserFiles.ts
- src/io/import/processors/handleDicomStream.ts
For this bug: #733
now this:
vs old message:
> feat: improve error messages for file loading

- src/core/streaming/cachedStreamFetcher.ts
When the entire stream finished but had no Content-Length header, treat full cache as total length.
Girder does not set Content-Length header in its response and we were fetching the entire stream twice.
> fix(cachedStreamFetcher): avoid double download

- src/core/streaming/dicom/dicomMetaLoader.ts
- src/core/streaming/dicom/dicomParser.ts
- src/core/streaming/streamingByteReader.ts
- dicom parser now exposes element hooks
- extract implicit or explicit VR
- build an empty PixelData tag for metadata parsing
> fix(dicom): build valid DICOM when reading tags

- src/components/SliceViewer.vue
- src/components/VolumeViewer.vue
- src/components/vtk/VtkSliceView.vue
- src/components/vtk/VtkVolumeView.vue
- src/store/view-configs/camera.ts
- src/utils/doubleKeyRecord.ts
> Stop double reseting camera on switching images or after loading from state file 

- src/components/tools/windowing/WindowLevelControls.vue
- src/composables/useWindowingConfig.ts
- src/composables/useWindowingConfigInitializer.ts
- src/core/streaming/dicomChunkImage.ts
- src/core/vtk/vtkFieldRef.ts
- src/io/import/processors/restoreStateFile.ts
- src/io/state-file/index.ts
- src/io/state-file/schema.ts
- src/store/image-stats.ts
- src/store/view-configs.ts
- src/store/view-configs/common.ts
- src/store/view-configs/types.ts
- src/store/view-configs/windowing.ts
- src/utils/allocateImageFromChunks.ts
Keeps the tag or auto histogram window level values from taking over if user already used range manipulator
Adds image-stats store to hold image range and histogram computations
> fix(windowing): no auto window level if user set already

- src/components/SegmentList.vue
- src/store/segmentGroups.ts
- src/store/tools/paint.ts
- src/store/tools/paintProcess.ts
- src/types/segment.ts
Adds lock/unlock buttons to individual segments to prevent them from accidental modification when painting other segments.
> feat(segments): add segment locking with paint protection

- src/components/ControlsModal.vue
- src/components/tools/paint/PaintWidget2D.vue
- src/composables/actions.ts
- src/config.ts
- src/constants.ts
Adds Ctrl+scroll (mouse wheel or two finger scroll) functionality to adjust paint brush size.
Related to #716!
> feat(PaintWidget2D): Add modifier+scroll shortcut for brush size

- src/components/DataBrowser.vue
Closes #729 
DICOM datasets with a missing or empty (0010,0010) PatientName tag were being processed with null value. This change now substitutes with `ANONYMOUS_PATIENT` when the value is not truthy
> fix(dicom): Normalize patient name for anonymous datasets

- CONTRIBUTING.md
This PR updates `CONTRIBUTING.md` to include environment prerequisites and a dependencies table.  
It helps contributors set up their environment correctly and avoid issues related to Node/npm/Vite compatibility.
- Added **Node.js** (>= 18.20.0, 20.x LTS recommended) and **npm** (>= 9.x) requirements
- Documented key dependencies from `package.json` (Vite, Vue, TypeScript, Vuetify, Pinia, vtk.js, itk-wasm, etc.)
- Added guidance for checking versions and regenerating `package-lock.json` if schema errors occur
- Kept existing setup, build, lint, test, and VTK.js development instructions intact
Closes #189
> docs: update CONTRIBUTING.md with prerequisites and dependencies table

- .env.example
- src/store/data-browser.ts
Closes #759
Configures the initial visibility state at build time. Can prevent a benign race condition between the default (true) and runtime-fetched (false) settings where delayed state update looks ugly.
> fix(config): Add sample data visibility env flag

- wdio.shared.conf.ts
It seems the flakiness was a result of the browser processes getting OOM-killed, and the harness not doing a great job of detecting or at least alerting about that fact.
> fix(test): reduce concurrency in E2E testing in CI
